### ISSUE TITLE
Hercules DJ console MK2 - Couldn't claim interface - Linux Mint 18.3 amd64

### ISSUE THREAD

**Issue by felix12oe** [nealey/hdjd#10]
When I start the driver with the DJ console MK2 (I know it may not work - the mixxx page says the Mk2 is supported by this driver- but the implementation in mixxx with the HID driver is not working fully) - I get the message:

Locating Hercules USB devices...
(You can also use the lsusb command to locate this information)
Vendor:Device = 06f8:b100
Opened [Hercules Hercules DJ Console Mk2]
usb.c:241 Fatal: Couldn't claim interface 1. Already in use?

I retried also as root - it's not working.

System is Linux Mint 18.3 amd64

An hints?

**Comment by nealey** [comment]
I would try rebooting to make sure nothing else has claimed it, then run hdjd before starting anything else. I unfortunately can't do much in hdjd if something else has grabbed the controller first, as this message indicates.

**Comment by statibk** [comment]
I had exactly the same problem with the Mk2 on Ubuntu 18.04, despite "hdjd" being the first thing being run after reboot.

I ended up using neither hdjd nor hdjmod-dkms but simply manually installed the udev rules as advised in <https://mixxx.org/wiki/doku.php/troubleshooting#hid_and_usb_bulk_controllers_on_gnu_linux> (and adapted the group settings to my setup). Then everything ran smoothly.

**Comment by nealey** [comment]
Solution seems to be to modify udev rules. Closing this 3-year-old issue :)
