### ISSUE TITLE
Hercules DJ 4 SET Support

### ISSUE THREAD

**Issue by watchingJu** [nealey/hdjd#13]
For anyone who is interested in support for the Hercules DJ 4 SET console, add the following to usb.c under devices:

``  { 0xb10c, 5, 0x83, 0x03, 0x84, 0}, // 4Set``

Needs more testing, but seems to work on Ubuntu 20.04

**Comment by nealey** [comment]
Holy cow, you were able to do what I was not. You got the 4Set working.

I verify it works with the 4Set Hercules mailed me that I thought was broken. Great work!

Would you like to submit a patch to add this, so your name is forever in the git repository? I'd be happy to walk you through the process if you haven't done it before.

**Comment by watchingJu** [comment]
I'm glad to help :) A friend who gave me the hardware managed to do it before on arch linux, but couldn't remember exactly how he did.

That gave me some motivation. I wasn't sure what I was doing, only added some outputs from ``lsusb`` which seemed reasonable and it worked on the first try ... but maybe that's how things are done.

I've never done a patch, but there is a pull request waiting.

**Comment by nealey** [comment]
Merged into the main codebase in https://github.com/nealey/hdjd/commit/627d5271142d226ccb559e66054397cac1a19f9a. Thank you!

**Comment by nealey** [comment]
https://github.com/nealey/hdjd/commit/627d5271142d226ccb559e66054397cac1a19f9a
