### ISSUE TITLE
Debug system

### ISSUE THREAD

**Issue by Mte90** [nealey/hdjd#6]
Actually hdjd write only that detected the controller but there are no other way to see if is getting the key pressing so I am not sure how debug the problem with mixxx.

**Comment by JosepMaJAZ** [comment]
Hello.

Yo can compile hdjd with the DEBUG define in order to get debug information. We didn't implement a way to get debug information from a commandline option.

**Comment by Mte90** [comment]
In the readme there aren't instruction for that :-/

**Comment by JosepMaJAZ** [comment]
You are correct. I simply forgot to do so. 
If you take a look at Makefile, there's this line commented:
#CFLAGS += -g -DDEBUG

Removing the # from the beginning will allow you to build a copy that will print input and output data.

I'll try to document it and see if i can make it even easier to do so.

**Comment by nealey** [comment]
The debugging that's currently in there is not going to be helpful for this issue, is it?

Seems like we should instead provide a verbosity argument, modify log.h to take an integer log level, remove DUMP calls, and add a high-verbosity log to display events.

**Comment by JosepMaJAZ** [comment]
Hi nealey.

Well, as I understood it, the DEBUG method could be enough. 
It prints exactly what is being received from the controller, and what is being sent to the controller, at the BULK level. It also enables the debug mode of libusb.

Ideally, yes, adding some log level system triggered with commandline arguments could improve the situation, but I'm not sure how to do so in an easy way.

**Comment by Mte90** [comment]
I compiled with the debug flag and now I get output like: `sent on ep03: 90 24 00` but Mixxx keep to not reconize when I press button.
Also on the shell where is running hdjd when I press something on the hercules nothing is happening. So seems something in the daemon but I can use the console without issue on windows.
In any case mixxx with `--controllerDebug` inform that everything is loaded for the console, but I was expecting to receive a log everytime I press a button on hdjd.

**Comment by nealey** [comment]
Those are the messages hdjd is getting from your controller. If you press a button and don't see a message on the console, then hdjd isn't seeing an event on the USB EP.

It would be helpful if you could tell us what controller you have, but at this point I think we can mark the original bug, about the debug system, closed. Please feel free to open a new issue telling us what controller you have and whether any buttons at all result in a debug message :)
