### ISSUE TITLE
Hercules DJ Control MP3 e2 doesn't reconize buttons pression

### ISSUE THREAD

**Issue by Mte90** [nealey/hdjd#9]
I compiled with the debug flag and now I get output like: sent on ep03: 90 24 00 but Mixxx keep to not reconize when I press button.
Also on the shell where is running hdjd when I press something on the hercules nothing is happening. So seems something in the daemon but I can use the console without issue on windows.
In any case mixxx with --controllerDebug inform that everything is loaded for the console, but I was expecting to receive a log everytime I press a button on hdjd.

**Comment by nealey** [comment]
Ah, the MP3 e2!

The MP3 e2 actually has native support in Mixxx. Have you tried getting that working first? I expect there's some sort of race condition between hdjd and mixxx both trying to use the same device. Also it would be a good idea to make sure your device permissions are set properly: this probably isn't the issue but it wouldn't hurt.

**Comment by Mte90** [comment]
Actually I am using Mixxx 2.0.0 and detect the console but with a different name.
Only when I execute hdjd, Mixxx load the hotkeys and the script, the native support seems doesn't reconize like hdjd.
I think that the problem is probably the same of hdjd because doesn't detect botton pressure.

**Comment by nealey** [comment]
I made a video for you: https://youtu.be/5KZkL0FvJV0

Does this help?

**Comment by Mte90** [comment]
Thanks for all the step!
Seems that my `/dev/bus/usb/001/004` has as group `users` and my user is in both (I mean also `plugdev`) the groups.

Seems that is an issue with udev, on https://raw.githubusercontent.com/mixxxdj/mixxx/master/res/linux/mixxx.usb.rules use `users` and not `plugdev`. I changed with `plugdev` and now `/dev/bus/usb/001/004` has `root` as user and group for access :-/

**Comment by nealey** [comment]
Were you able to get everything working?

**Comment by nealey** [comment]
If you're in the group of that device, your permissions are set properly. In any case if you were to run hdjd as root it shouldn't matter what permissions are.

When you press the cue button, do you see the debug output?

**Comment by Mte90** [comment]
Uhm now I have the plugdev group on the dev.
Running hdjd as root is not happening nothing.

Maybe adding something on hdjd that detect if the user has the right permission can be helpful for debugging.

**Comment by nealey** [comment]
If you don't have the right permissions it won't detect anything, and exit.

Will you please run the `explore` program built in the same directory, press the lower-left CUE button, hit Control-C, and paste the output?

**Comment by Mte90** [comment]
I get only:
```root@laptop:/tmp/hdjd# ./explore 
Opened a Hercules DJ Control MP3 e2
```
I pressed all the button to be sure.

```root@laptop:/tmp/hdjd# ./hdjd 
Locating Hercules USB devices...
(You can also use the lsusb command to locate this information)
Vendor:Device = 06f8:b105
Opened [Hercules DJ Control MP3 e2]
^Chdjd.c:58 
Exiting...```

**Comment by nealey** [comment]
Well that is very interesting. Your device may be in some sort of mode I don't yet understand.

Can you paste the output of `sudo lsusb -v`? You can omit everything but the section starting with ID 06f8:b105 if you like. I want to verify that there's not some new firmware on this device causing the bulk interface to go away..

**Comment by Mte90** [comment]
```Bus 001 Device 004: ID 06f8:b105 Guillemot Corp. 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x06f8 Guillemot Corp.
  idProduct          0xb105 
  bcdDevice            1.09
  iManufacturer           1 Hercules
  iProduct                2 DJ Control MP3 e2
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           48
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000c  1x 12 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000c  1x 12 bytes
        bInterval               0
Device Status:     0x0000
  (Bus Powered)
```

This console is quite old maybe I bought on 2009/2010 but I am not sure.

**Comment by nealey** [comment]
Rats. That looks normal.

I expect there is some sort of initialization packet I need to send the thing; this may be why Guillemot thought the 4set was going to work for me, and I was unable to get it working.

If anybody would like to look into this, I'd start by poring over their released Linux kernel driver code (even though it's old) to check whether there's some sort of initialization that needs to happen before the thing gets going. It's possible the Windows driver got it into some different mode, and we need to set it back.

**Comment by Mte90** [comment]
any updates?

**Comment by nealey** [comment]
I won't be able to help much until around August at the earliest, sorry.

**Comment by tryger** [comment]
Same error here. When I open endpoint 0x81, libusb gets input (crab for midi), but 0x82 doesn't get any input.

I wrote a test program that just reads the endpoint 0x82, and I receive the correct input.

Any idea?

**Comment by nealey** [comment]
Well, I guess we need to set the endpoint to 0x82 then. I'll try that with my controller to make sure we don't break anything, and if it looks good, I'll push a change.

I should mention that I'm years past actively using these controllers for anything at all, hdjd needs a new maintainer.

**Comment by Mte90** [comment]
I finally got working the Hercules with Mixxx downloading the source and compiling them, so this daemon is not required anymore with this software.

**Comment by twitwi** [comment]
I changed in `usb.c` :

     { 0xb105, 1, 0x81, 0x03, 0x0, 0 }, // MP3e2

and I'm now getting events (not use it much yet).

**Comment by nealey** [comment]
I'm going to put out another call for a maintainer who actually uses a controller. This bug is over 3 years old now and I still haven't had a chance to test out changing the endpoint.

**Comment by makuser** [comment]
> I'm going to put out another call for a maintainer who actually uses a controller. This bug is over 3 years old now and I still haven't had a chance to test out changing the endpoint.

The endpoint 0x81 is correct.

**Comment by nealey** [comment]
Awesome, thank you.

I don't suppose you'd like your very own open source package maintanership? 😉

**Comment by nealey** [comment]
Oh, wait, i should verify that the correct code is in the repo first, then close this ticket.
